library(ggplot2)

SAVE <- function(plt, path_dropbox, path_overleaf, h = 6.3, w = 7.5){
  ggsave(plot = plt, filename = paste0("theory/empirical_facts/04_results/", path_dropbox), dpi = 600, height = h, width = w, bg = "white")
  ggsave(plot = plt, filename = paste0("../Apps/Overleaf/tradeDeforestation/", path_overleaf), dpi = 600, height = h, width = w, bg = "white")
}

scale_color <-   scale_color_manual(values = c("fcuhom" = "black", 
                                                          "otherpub" = "red",
                                                          "nonhom" = "brown",
                                                          "nonpub" = "deepskyblue",
                                                          "otherpubforest" = "#FF8080",
                                                          "otherpubnotforest" = "darkred",
                                                          "pubpermforest" = "grey",
                                                          "pubpermnotforest" = "grey14",
                                                          "forest" = "#FF8080",
                                                          "notforest" = "darkred"),
                                               breaks = c("fcuhom", 
                                                          "otherpub",
                                                          "nonhom",
                                                          "nonpub",
                                                          "otherpubforest",
                                                          "otherpubnotforest",
                                                          "pubpermforest",
                                                          "pubpermnotforest",
                                                          "forest",
                                                          "notforest"),
                                               labels = c("Perpetual Public", 
                                                          "Other Public",
                                                          "Not Legalized IT",
                                                          "Not Public",
                                                          "Forest in t-2",
                                                          "Not Forest in t-2",
                                                          "Forest in t-2",
                                                          "Not Forest in t-2",
                                                          "Forest in t", 
                                                          "Not Forest in t"))

scale_fill <-   scale_fill_manual(values = c("fcuhom" = "black", 
                                               "otherpub" = "red",
                                               "nonhom" = "brown",
                                               "nonpub" = "deepskyblue",
                                               "otherpubforest" = "#FF8080",
                                               "otherpubnotforest" = "darkred",
                                               "pubpermforest" = "grey",
                                               "pubpermnotforest" = "grey14",
                                               "forest" = "#FF8080",
                                               "notforest" = "darkred"),
                                    breaks = c("fcuhom", 
                                               "otherpub",
                                               "nonhom",
                                               "nonpub",
                                               "otherpubforest",
                                               "otherpubnotforest",
                                               "pubpermforest",
                                               "pubpermnotforest",
                                               "forest",
                                               "notforest"),
                                    labels = c("Perpetual Public", 
                                               "Other Public",
                                               "Not Legalized IT",
                                               "Not Public",
                                               "Forest in t-2",
                                               "Not Forest in t-2",
                                               "Forest in t-2",
                                               "Not Forest in t-2",
                                               "Forest in t", 
                                               "Not Forest in t"))

scale_fill_mapbiomes <-   scale_fill_manual(values = c("Vegetated" = "#1b7837", 
                                                        "Non-Vegetated" = "#f6e8c3",
                                                        "water" = "navy"),
                                             breaks = c("Vegetated", 
                                                        "Non-Vegetated"),
                                             labels = c("Vegetated", 
                                                        "Non-Vegetated"))

scale_fill_mapbiomes2 <-   scale_fill_manual(values = c("Vegetated" = "#1b7837",
                                                       "Pasture" = "#f6e8c3",
                                                       "Other Non-Vegetated" = "#fdae61",
                                                       "water" = "navy",
                                                       "novege_area" = "gray25"),
                                            breaks = c("Vegetated", 
                                                       "Pasture",
                                                       "Other Non-Vegetated"),
                                            labels = c("Vegetated",
                                                       "Pasture",
                                                       "Other Non-Vegetated"))

scale_fill_mapbiomes_predicted <-   scale_fill_manual(values = c("Vegetated" = "#1b7837", 
                                                       "pasture" = "#f6e8c3",
                                                       "water" = "navy",
                                                       "soy" = "#fdae61"),
                                            breaks = c("Vegetated", 
                                                       "pasture",
                                                       "soy"),
                                            labels = c("Vegetated", 
                                                       "Pasture",
                                                       "Soy"))
scale_fill_mapbiomes_predicted2 <-   scale_fill_manual(values = c("Vegetated" = "#1b7837", 
                                                                 "pasture" = "#f6e8c3",
                                                                 "water" = "navy",
                                                                 "soy" = "#fdae61",
                                                                 "Predicted Deforestation" = "red",
                                                                 "Deforestation" = "red"),
                                                      breaks = c("Vegetated", 
                                                                 "pasture",
                                                                 "soy",
                                                                 "Predicted Deforestation",
                                                                 "Deforestation"),
                                                      labels = c("Vegetated", 
                                                                 "Pasture",
                                                                 "Soy",
                                                                 "Predicted Deforestation",
                                                                 "Deforestation"))

scale_fill_mapbiomes_predicted3 <-   scale_fill_manual(values = c("FF" = "#1b7837",
                                                                  "Vegetated" = "#1b7837",
                                                                  "Non-Vegetated" ="#f6e8c3",
#                                                                  "soy" = "#fdae61",
                                                                  "water" = "navy",
                                                                  "DF" = "black",
                                                                  "FD" = "gray35",
                                                                  "DD" = "#FF1A1A",
                                                                  "novege" = "gray25"),
                                                       breaks = c("FD",
                                                                  "DD",
                                                                  "DF"),
                                                       labels = c("Predicted: Incorrect",
                                                                  "Predicted: Correct",
                                                                  "Non-Predicted"))

scale_shape <-  scale_shape_manual(values = c(fcuhom = 18,  
                                                         otherpub = 15,
                                                         nonhom = 16,
                                                         nonpub  = 17,
                                                         otherpubforest=15,
                                                         otherpubnotforest=15,
                                                         pubpermforest=18,
                                                         pubpermnotforest=18,
                                                         forest=15,
                                                         notforest=15), 
                                              breaks = c("fcuhom",
                                                         "otherpub",
                                                        "nonhom",
                                                        "nonpub",
                                                        "otherpubforest",
                                                        "otherpubnotforest",
                                                        "pubpermforest",
                                                        "pubpermnotforest",
                                                        "forest",
                                                        "notforest"),
                                              labels = c("Perpetual Public",
                                                        "Other Public", 
                                                        "Not Legalized IT",
                                                        "Not Public",
                                                        "Forest in t-2",
                                                        "Not Forest in t-2",
                                                        "Forest in t-2",
                                                        "Not Forest in t-2",
                                                        "Forest in t", 
                                                        "Not Forest in t"))
theme_raw_stats <- theme_classic() +
                   theme(legend.position = "bottom",
                         panel.grid.major.y = element_line(linetype = 2, colour = "grey70"),
                         legend.text=element_text(size=14),
                         legend.title=element_text(size=13.5),
                         plot.title = element_text(hjust = 0.5, size=14,face="bold"),
                         plot.subtitle = element_text(hjust = 0.5, size=14,face="bold"),
                         axis.text = element_text(size = 12*1.25, face = "bold"),
                         axis.title = element_text(size = 15))

theme_es <- theme_classic() +
            theme(legend.position = "bottom",
                  panel.grid.major.y = element_line(linetype = 2, colour = "grey70"),
                  legend.key = element_blank(),
                  legend.text=element_text(size=14),
                  legend.title=element_text(size=13.5),
                  plot.title = element_text(hjust = 0.5, size=14,face="bold"),
                  plot.subtitle = element_text(hjust = 0.5, size=14,face="bold"),
                  axis.text = element_text(size = 12*1.25, face = "bold"),
                  axis.title = element_text(size = 15))

